//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int idc { get; set; }
        public string nomC { get; set; }
        public int idr { get; set; }
    
        public virtual Reservations Reservations { get; set; }
    }
}
