//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservations()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int id { get; set; }
        public int chambre { get; set; }
        public string agence { get; set; }
        public System.DateTime Arrivee { get; set; }
        public string nat { get; set; }
        public int nombre { get; set; }
        public float montant { get; set; }
        public string bons { get; set; }
        public System.DateTime dft { get; set; }
        public string type { get; set; }
        public string methpaie { get; set; }
        public bool comfirmed { get; set; }
        public string devise { get; set; }
        public float montantpn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Revenus Revenus { get; set; }
    }
}
